### ISSUE TITLE
Feature 1: The NorJS Command Line Interface

### ISSUE THREAD

**Issue by thejhh** [norjs/web-client#1]
This is a feature issue which maps required tasks.

### Description

Command line utility which can be used to run the development system and build production apps.

### Required Tasks

  * [ ]  Task #9: Enable HTML title customization for views
  * [ ]  Task #17: nrNavService
  * [ ]  Task #11: Enable SCSS customization
  * [ ]  Task #4: Rename global NorJS constants better
  * [ ]  Task #20: norjs build should have option to change dist location

### Optional Tasks

  * [ ]  Task #21: Restart development mode on changes to custom app.json
  * [ ]  Task #7: Enable custom index.html
  * [ ]  Task #12: Enable changing HTML lang tag
  * [ ]  Task #14: Improve nr-nav
  * [ ]  Task #10: Enable ng-app name customization in index.html
  * [ ]  Task #5: Enable custom translations
  * [ ]  Task #6: Rename PREFERRED_LANGUAGE
  * [ ]  Task #13: Better MainViewController
  * [ ]  Task #15: Improve nr-compile
  * [ ]  Task #16: Rename .registerLifeCycleMethods
  * [ ]  Task #18: Enable server port customizations

### Finished tasks

  * [x]  Bug #19: Development server does not shutdown when norjs exists
  * [x]  Task #8: Enable custom AngularJS modules
  * [x]  Task #2: Command Line Interface
  * [x]  Task #3: test.mocks must be renamed
